Allow passing `None` to `Experiment.axis_query`.
single-cell-data/SOMA pull request #99
Opened 2023-01-24 20:31 UTC by thetorpedodog

cf. #98

2023-01-24 22:10 UTC, atolopko-czi requested changes
A concern noted in comments.

2023-01-24 22:10 UTC, atolopko-czi commented on python-spec/src/somacore/experiment.py
> +        var_query: Optional[query.AxisQuery] = None,
docstring for this method indicates `See :class:`query.ExperimentAxisQuery` for details on usage`.  But in fact I think the problem will still persist in `somacore` code.  If caller of this methods specifies `None`, somacore will not convert that to AxisQuery().  Does the fix need to be pushed down into somacore perhaps? Either way, suggest adding a test in this repo to ensure correct behavior.

2023-01-25 00:15 UTC, bkmartinjr approved these changes
this looks great - ty

2023-01-25 15:05 UTC, merged

2023-01-25 15:57 UTC, bkmartinjr commented
> LGTM. Should we also add a corresponding unit test in TileDB-SOMA repo?

_Please_ add a test - the lack of them was why we missed this regression previously.